<?php
// ---------------------------------
// JAVASCRIPT
// --------------------------------- 
$this->jQuery()->onLoadCaptureStart(); ?>

        $(document).on("keyup", ".onlyDecimals", function() {
            var newValue = $(this).val().replace(/[^0-9\.,]/g,'');
            $(this).val(newValue);
        });

        // Voeg toe aan winkelmand
       $("#VoegToe").click(function(event) {
     	event.preventDefault();
     	$("#divLoading").html('<img src="/base/images/icons/loader_02.gif" /><BR> Loading, please wait...');
        $("#VoegToe").hide();
        var myForm    =  $(this).closest('form');
        var formId    =  myForm.attr('id');
        var formdata  = myForm.serialize();

        $.ajax({
          type: "POST",
          dataType: "json",
          url: "<?php echo $this->baseUrl() . '/index/ajax-voegtoe-winkelmand/'; ?>",
          dataType: "html",
          data: {data: formdata },
          success: function(html){
                            if (html == '1') {
                                alert("Fout bij validatie formulier");
                            }
                            else {
                                //location.href="/index/home/";
                                $('.winkelmand').empty().append(html);
                            }
                            $("#VoegToe").show();
                            $("#divLoading").html('');
          		}
           });
	   return false;
       });
<?php 
$this->jQuery()->onLoadCaptureEnd();
?>