<?php 
echo $this->headLink()->prependStylesheet('/base/datagrid/styles/default.css');
if (!empty($this->messages)){
	echo '<div class="msg_ok" style="color:white;">';
	//echo '<ul>';
		$counter = 0;
		foreach($this->messages as $v){
		//	echo '<li> ' . $this->escape($v) .'</li>' . PHP_EOL;	
			//echo ++$counter.'. ' . $this->escape($v) . PHP_EOL;
			echo $this->escape($v) . '<br />' .  PHP_EOL;
		}
	//echo '</ul>';
	echo '</div>';
}
?>

<div style="width:1180px;overflow:auto;">
    <?php
        echo $this->dataGrid;
    ?>
</div>